Asp.NetCore/Asp.NetCore.IdentityDemo/Controllers/SysController.cs
using System.Threading.Tasks;
using Asp.NetCore.IdentityDemo.Services.Impl;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Asp.NetCore.IdentityDemo.Controllers
{
    [Authorize]
    public class SysController : Controller
    {

        private readonly AppRoleManager _appRoleManager;

        public SysController(AppRoleManager appRoleManager)
        {
            _appRoleManager = appRoleManager;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> AddRole(IdentityRole identityRole)
        {
            var role = identityRole??new IdentityRole();
            var result = await _appRoleManager.CreateAsync(role);
            return new JsonResult(new {Successed = result.Succeeded, Errors = result.Errors});
        }


    }
}

Asp.NetCore/Asp.NetCore.IdentityDemo/Views/Sys/Index.cshtml
<form asp-controller="Sys" asp-action="AddRole"  method="post" class="form-horizontal" role="form">
    <h4>Use a local account to log in.</h4>
    <hr />
    <div class="form-group">
        <div class="col-md-10">
            <input type="text" name="Name"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Log in</button>
        </div>
    </div>
   
</form>